CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    role_id BIGINT NOT NULL,
    CONSTRAINT fk_users_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS user_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    full_name VARCHAR(255),
    avatar_url VARCHAR(255),
    bio VARCHAR(255),
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS playlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_private BOOLEAN DEFAULT FALSE,
    is_deleted BOOLEAN DEFAULT FALSE,
    user_id BIGINT,
    CONSTRAINT fk_playlists_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    video_url VARCHAR(255) NOT NULL,
    thumbnail_url VARCHAR(255),
    status VARCHAR(20) DEFAULT 'public',
    view_count INTEGER DEFAULT 0,
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    CONSTRAINT fk_videos_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_videos_category
        FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE,
    user_id BIGINT,
    video_id BIGINT,
    parent_id BIGINT,
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_comments_video
        FOREIGN KEY (video_id) REFERENCES videos (id),
    CONSTRAINT fk_comments_parent
        FOREIGN KEY (parent_id) REFERENCES comments (id)
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT,
    channel_owner_id BIGINT,
    CONSTRAINT fk_subscriptions_follower
        FOREIGN KEY (follower_id) REFERENCES users (id),
    CONSTRAINT fk_subscriptions_channel_owner
        FOREIGN KEY (channel_owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS playlist_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT,
    video_id BIGINT,
    CONSTRAINT fk_playlist_videos_playlist
        FOREIGN KEY (playlist_id) REFERENCES playlists (id),
    CONSTRAINT fk_playlist_videos_video
        FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE TABLE IF NOT EXISTS video_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    video_id BIGINT,
    type VARCHAR(10),
    CONSTRAINT fk_video_reactions_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_video_reactions_video
        FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE TABLE IF NOT EXISTS video_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_id BIGINT,
    tag_id BIGINT,
    CONSTRAINT fk_video_tags_video
        FOREIGN KEY (video_id) REFERENCES videos (id),
    CONSTRAINT fk_video_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags (id)
);

CREATE TABLE IF NOT EXISTS watch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    video_id BIGINT,
    last_position INTEGER DEFAULT 0,
    CONSTRAINT fk_watch_history_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_watch_history_video
        FOREIGN KEY (video_id) REFERENCES videos (id)
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS idx_user_profiles_user_id ON user_profiles (user_id);
CREATE INDEX IF NOT EXISTS idx_playlists_user_id ON playlists (user_id);
CREATE INDEX IF NOT EXISTS idx_videos_user_id ON videos (user_id);
CREATE INDEX IF NOT EXISTS idx_videos_category_id ON videos (category_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments (user_id);
CREATE INDEX IF NOT EXISTS idx_comments_video_id ON comments (video_id);
CREATE INDEX IF NOT EXISTS idx_comments_parent_id ON comments (parent_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_follower_id ON subscriptions (follower_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_channel_owner_id ON subscriptions (channel_owner_id);
CREATE INDEX IF NOT EXISTS idx_playlist_videos_playlist_id ON playlist_videos (playlist_id);
CREATE INDEX IF NOT EXISTS idx_playlist_videos_video_id ON playlist_videos (video_id);
CREATE INDEX IF NOT EXISTS idx_video_reactions_user_id ON video_reactions (user_id);
CREATE INDEX IF NOT EXISTS idx_video_reactions_video_id ON video_reactions (video_id);
CREATE INDEX IF NOT EXISTS idx_video_tags_video_id ON video_tags (video_id);
CREATE INDEX IF NOT EXISTS idx_video_tags_tag_id ON video_tags (tag_id);
CREATE INDEX IF NOT EXISTS idx_watch_history_user_id ON watch_history (user_id);
CREATE INDEX IF NOT EXISTS idx_watch_history_video_id ON watch_history (video_id);

INSERT INTO roles (name, is_deleted)
VALUES
    ('ROLE_USER', FALSE),
    ('ROLE_ADMIN', FALSE)
ON CONFLICT (name) DO NOTHING;