# Activate with: --spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/lamtube
spring.datasource.username=postgres
spring.datasource.password=postgres

app.jwt.secret-key=TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
app.jwt.access-expiration-seconds=900
app.jwt.refresh-expiration-seconds=2592000
app.auth.refresh-token-ttl-days=30
app.auth.cookie.refresh-token-name=refresh_token
app.auth.cookie.refresh-token-max-age-seconds=2592000
app.auth.cookie.secure=false
app.auth.cookie.same-site=Lax
app.auth.cookie.path=/api

app.cors.allowed-origins=http://localhost:5173

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}

rustfs.access-key=rustfsadmin
rustfs.secret-key=rustfsadmin
rustfs.bucket-name=lamtube
rustfs.internal-url=http://localhost:9000
rustfs.public-url-prefix=http://localhost:9000
